### PR TITLE
[WORK IN PROGRESS] Added initial compatibility for XT3

### PR DESCRIPTION
**Pull request by mweimerskirch**
Work in Progress. Do note merge yet.

I added initial compatibility for XT3.
The goal was to change as less code as possible, in order to keep the XT1 compatibility intact. I added an additional argument "--model" to the command line and an additional "model" argument to the Lupusec.__init__ method. Accepted values are "xt1" (default) or "xt3".

A few constants were converted to variables (e.g. MODE_TRANSLATION) because they are different for each device. Apart from that, only a few "if"-statements were needed throughout the code.

What works so far:
- reading the sensors and their status
- reading the panel mode (disarm, arm, home)
- setting the panel mode (disarm, arm, home)
- command line access

What doesn't work:
- So far only area 1 is supported. If you've configured multiple areas, you currently won't be able to use them.
- Home Assistant integration is yet to be tested.
- I can't test the power switches functionality as I don't have any.
- Detecting an alarm (through the "history" of the panel).

I can only work on this during the weekends, so not sure when I'll be able to finalize the implementation, but I still wanted to publish the current status in case anybody wanted to join in.

### CODE REVIEW

**Comment by majuss** [comment]
Thank you very much for your efforts! I'am glad to see that somebody is interested to develop this further :) I will do my best to keep the merging process as smooth as possible, but sadly I have no access to XT3 hardware (the XT1 was only a few bucks) so my possibilities to help you are very limited.

Just keep me updated when you think it's production ready.

**Comment by majuss** [comment]
After looking at your code, here are my initial thoughts: We should be able to automatically detect the XT version. There should be a hint on the landing page (pre-login). And we can safely assume that nobody ever has two different versions of the XT in the same household :)

Til now (I know it's early alpha, but better say something early) you're catching the model with a lot of "ifs" I think we should integrate a better way in the long run. One idea would be a CONST file with all the XT specific Consts that we deal with. And then when the XT is detected we just switch the CONST files (so from const_xt1.py to const_xt3.py) and thats it :)

**Comment by saibotk** [comment]
As far as i can see it, the compatibility for the XT3 also works for the XT2Plus. I will test this further, and try to make it compatible if not supported already.

**Comment by mweimerskirch** [comment]
Sorry for not getting back to you earlier.

> After looking at your code, here are my initial thoughts: We should be able to automatically detect the XT version. There should be a hint on the landing page (pre-login). And we can safely assume that nobody ever has two different versions of the XT in the same household :)

The XT3 does not have a login page, but the login is done using a HTTP authentication window. We could check if there is a login page or if there is a HTTP auth request, but I'm not sure this is a reliable way to detect the model. Personally, I would opt to make users specify this manually.

> Til now (I know it's early alpha, but better say something early) you're catching the model with a lot of "ifs" I think we should integrate a better way in the long run. One idea would be a CONST file with all the XT specific Consts that we deal with. And then when the XT is detected we just switch the CONST files (so from const_xt1.py to const_xt3.py) and thats it :)

I agree that the IFs are not a good solution. However, I fear that using two files with constants that are loaded dynamically limits edge cases where someone might be using two different models. Also constants do not solve the issue where the functionality of the XT1 and XT3 is different. An alternative solution might be to work with inheritance and put the XT3-spefic code into a subclass (e.g. called "LupusecXT3" which would inherit most code from the main "Lupusec" class).
Then, the call to the constructor would be put in an "if" statement that would look something like this (pseudo-code):

```
if model=xt3
    lupusec = lupupy.LupusecXT3(...)
else
    lupusec = lupupy.Lupusec(...)
```

That would be a very clean solution, although it would require more refactoring

> As far as i can see it, the compatibility for the XT3 also works for the XT2Plus. I will test this further, and try to make it compatible if not supported already.

@saibotk any updates on testing with the XT2Plus?


One more point: I think it would be a good idea to collect example output from the different models inside of the repository (with all IDs anonymized for security reasons). That would make it easier for one developer to see the effects of his changes on other models and also might allow automated tests in the future. What do you think?

**Comment by saibotk** [comment]
I will take a look at the compatibility with the XT2Plus either this evening or this weekend, depending on when I got some time to test it. What I identified for now was, that they both use the same auth method and my first api responses seemed to be identicial or at least pretty reasonable to function with your code adjustments.

Regarding your notes on refactoring: 
I think implementing inhertance would be the right step, even if this is a fairly small project, who knows, when there will be other Api changes or new lupus devices. In all regards, it would increase the extensibility and readability. Also this would further improve testability of the code for different devices.

**Comment by majuss** [comment]
@saibotk @mweimerskirch I will start the gathering of general infos on the different XT models in the coming days (let's hope not weeks :D) and maybe I start the refactoring process. Is anyone willing to help me:)?

**Comment by saibotk** [comment]
@majuss i would, sorry i also was pretty busy and forgot about it. But since python is not one of my most fluent languages, i cannot help much with language specific patterns etc. I could still help out in the refactoring process, when discussing the general structure etc.. or testing this with the XT2Plus :+1: 
Nice to see some interest in this again :P

**Comment by mweimerskirch** [comment]
@majuss I can provide information about the XT3 (e.g. example output from the API endpoints) and run tests. Not sure how much I can currently help with coding as time is a bit limited right now.

**Comment by majuss** [comment]
I would really like to work on this.. but without the device at my home it's somewhat impossible :(

**Comment by Airbrando** [comment]
Hoe can i test it with my xt2 plus ? Ive home assistant and a xt2 plus @ home. It would be awesome when the xt2 plus would work.

**Comment by Airbrando** [comment]
> As far as i can see it, the compatibility for the XT3 also works for the XT2Plus. I will test this further, and try to make it compatible if not supported already.

How can i test it ? Please help 😊

**Comment by majuss** [comment]
So in short: you clone this branch onto your machine: https://github.com/mweimerskirch/lupupy/tree/xt3_compatibility activate your HA venv and install the cloned code with: `pip3 install .`

**Comment by Airbrando** [comment]
> So in short: you clone this branch onto your machine: https://github.com/mweimerskirch/lupupy/tree/xt3_compatibility activate your HA venv and install the cloned code with: `pip3 install .`

Can you explain me how to clone this branch ? The install with pip3 is working in the terminal right ? Thanks for your Help

**Comment by majuss** [comment]
So you connect to your HA core machine. Then switch to your homeassistant user and activate the venv:
```
sudo -u homeassistant -H -s
source /srv/homeassistant/bin/activate
git clone --single-branch --branch xt3_compatibility https://github.com/mweimerskirch/lupupy.git
cd lupupy
pip3 install .
```
After that you need to edit your HA `configuration.yaml` and restart HA

**Comment by Airbrando** [comment]
> So you connect to your HA core machine. Then switch to your homeassistant user and activate the venv:
> 
> ```
> 
> sudo -u homeassistant -H -s
> 
> source /srv/homeassistant/bin/activate
> 
> git clone --single-branch --branch xt3_compatibility https://github.com/mweimerskirch/lupupy.git
> 
> cd lupupy
> 
> pip3 install .
> 
> ```
> 
> After that you need to edit your HA `configuration.yaml` and restart HA
> 
> 

Thank you very much. And this does also work partialy with the xt2 plus ? Do i need to edit the configuration.yaml like you postet it ? Or is it different ?

**Comment by majuss** [comment]
You have to try it out... I only have the XT1.

**Comment by Airbrando** [comment]
> You have to try it out... I only have the XT1.

Ok. Thank you very much so far. Will this project go on or is it not continued ?

And did you mean with the venv the terminal ?

**Comment by majuss** [comment]
venv = Python virtual environment. You have to run all these commands in a terminal. The project is on hold and the continuation is questionable.

**Comment by mweimerskirch** [comment]
Unfortunately, I never got the time to continue working on this. This week, I decided to try my own approach and I implemented an MQTT based integration. It's available on my Github profile: https://github.com/mweimerskirch/lupus-to-mqtt

As I no longer have the need for XT3 support in this library, I'm closing the pull request. If anybody is interested in continuing the work, feel free to clone the branch linked to this pull request. Please be aware that at some point in the future I might delete my copy of the lupupy repo from my Github account.

**Pull request closed without merging**
